### 注册
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "username": "luo1333",
    "password": "123456789"
}

### 登录
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "leslie",
    "password": "123456"
}

### 登录后才可访问
POST http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxlc2xpZSIsInN1YiI6ImM0ZDAyYzU2LTZmYzktNDgyNy04OTkxLWVmZjA0ZmE3ODQxNiIsImlhdCI6MTY5MzA1ODA3MCwiZXhwIjoxNjkzMDY1MjcwfQ.LPb-Hb8ub_448UYIrRjkCREbjWW_9xaUGuVqzY48W40